import { ReactNode } from 'react';
import { ChakraProvider } from '@chakra-ui/react';

export const metadata = {
  title: 'My Next.js App with Chakra UI',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
      <html lang="en">
      <body>
      <ChakraProvider>
        {children}
      </ChakraProvider>
      </body>
      </html>
  );
}
